### ISSUE TITLE
CFLAGS not compatible with aarch64

### ISSUE THREAD

**Issue by Mic92** [jarun/bcal#17]
specifying `-m64` breaks aarch64 support: https://github.com/NixOS/nixpkgs/pull/35230#issuecomment-367101196

**Comment by jarun** [comment]
@szlin, we added this flag at https://github.com/jarun/bcal/commit/949bc1836b325e6d2a9887a988e097fee8484e0e#diff-b67911656ef5d18c4ae36cb6741b7965.
Is this necessary for Debian builds? (or we added it just to ensure someone compiling it on a 32-bit system can get it compiled?)

Note that we do mention the following in the README:

`Only 64-bit operating systems are supported.`

**Comment by Mic92** [comment]
Arm64 is a 64-bit architecture. However `-m64` is an x86 only gcc option: https://gcc.gnu.org/onlinedocs/gcc-4.5.3/gcc/i386-and-x86_002d64-Options.html

**Comment by jarun** [comment]
True. I am trying to get the context from @szlin on why we added it.

**Comment by jarun** [comment]
OK, I found this note from @szlin [here](https://github.com/jarun/bcal/pull/5#issuecomment-256363662):

_@jarun The purpose of this patch is to avoid compiling error in x86 environment. It is not related with SID, one of my PC is x86-based; therefore, I added this flag._

So I believe @szlin won't be offended if we remove it. He seems to be a nice guy! ;)

I'll make the change in a few minutes.

**Comment by jarun** [comment]
Done! @szlin can use the new target `x86` for his use case.
