### ISSUE TITLE
Source code release tarball?

### ISSUE THREAD

**Issue by ibara** [jarun/bcal#20]
Hi --

Is it possible for you to upload a source tarball alongside your package tarballs, like you do for nnn? I would like to make a package of bcal for OpenBSD, and we have learned that the GitHub auto-generated source tarballs can change unexpectedly.

**Comment by jarun** [comment]
Can you please raise a PR to do that?

**Comment by jarun** [comment]
I have pushed the changes to master. It might take a while till the next release.

**Comment by ibara** [comment]
Thank you, I appreciate that. It's OK if it takes a while until next release.
