### ISSUE TITLE
One test fails on FreeBSD

### ISSUE THREAD

**Issue by 0mp** [jarun/bcal#23]
```
./bcal -b '9876543210.987654321 * 123456789.123456789'
```
returns
> bc: stdin:2: syntax error: = unexpected

Here's the failure message from the test suite:

> ```
> =================================================================================================================================== FAILURES ====================================================================================================================================
> ______________________________________________________________________________________________________________ test_output[item64-1219326312467611632.3609205901
> ] ______________________________________________________________________________________________________________
> 
> item = ('./bcal', '-b', '9876543210.987654321 * 123456789.123456789'), res = b'1219326312467611632.3609205901\n'
> 
>     @pytest.mark.parametrize('item, res', zip(test, res))
>     def test_output(item, res):
>         try:
>             out = subprocess.check_output(item, stderr=subprocess.STDOUT)
>         except subprocess.CalledProcessError as e:
>             # print(e.output)
>             assert e.output == res
>         else:
> >           assert out == res
> E           AssertionError: assert b'bc: stdin:2... unexpected\n' == b'121932631246....3609205901\n'
> E             At index 0 diff: 98 != 49
> E             Left contains more items, first extra item: 101
> E             Use -v to get the full diff
> 
> test.py:184: AssertionError
> ====================================================================================================================== 1 failed, 71 passed in 0.44 seconds ======================================================================================================================
> *** Error code 1
> ```

**Comment by 0mp** [comment]
I guess it might be due to the fact that `bcal` uses some nonstandard bc(1) operations that are not supported by FreeBSD [bc(1)](https://www.freebsd.org/cgi/man.cgi?bc).

**Comment by jarun** [comment]
Please test on latest master and confirm it works for you.

**Comment by 0mp** [comment]
No, it didn't solve the problem. :/

**Comment by jarun** [comment]
That's weird. There's no other option used!
Could you try to debug a little? I don't use BSD.

**Comment by 0mp** [comment]
Sure! Hang on! ;)

**Comment by jarun** [comment]
Just run the operation and share what you get.

**Comment by 0mp** [comment]
> ```
> _________________________________________ test_output[item64-1219326312467611632.3609205901
> ] _________________________________________
> 
> item = ('./bcal', '-b', '9876543210.987654321 * 123456789.123456789'), res = b'1219326312467611632.3609205901\n'
> 
>     @pytest.mark.parametrize('item, res', zip(test, res))
>     def test_output(item, res):
>         try:
>             out = subprocess.check_output(item, stderr=subprocess.STDOUT)
>         except subprocess.CalledProcessError as e:
>             # print(e.output)
>             assert e.output == res
>         else:
> >           assert out == res
> E           AssertionError: assert b'bc: stdin:2... unexpected\n' == b'121932631246....3609205901\n'
> E             At index 0 diff: 98 != 49
> E             Left contains more items, first extra item: 101
> E             Full diff:
> E             - b'bc: stdin:2: syntax error: = unexpected\n'
> E             + b'1219326312467611632.3609205901\n'
> 
> test.py:184: AssertionError
> ================================================= 1 failed, 71 passed in 0.46 seconds =================================================
> *** Error code 1
> ```

**Comment by jarun** [comment]
I meant just run:

    ./bcal -b '9876543210.987654321 * 123456789.123456789'

**Comment by jarun** [comment]
Ahh ok, I get the full diff. But run the command standalone anyway.

**Comment by 0mp** [comment]
I believe that the problem is with

```
	if (write(pipe_pc[1], "last=", 5) != 5) {
		log(ERROR, "write(2)! [%s]\n", strerror(errno));
		exit(-1);
	}
```

because `echo 'last=' | bc` gives:

> bc: stdin:1: syntax error: = unexpected

When it comes to the bcal command though:

```console
$ /usr/local/bin/bcal -b '9876543210.987654321 * 123456789.123456789'
bc: stdin:2: syntax error: = unexpected

```

**Comment by jarun** [comment]
But after that we do write the value of `lastres` and a newline so I am not sure why it should be a problem.

**Comment by 0mp** [comment]
```console
$ echo 'last=1' | bc
bc: stdin:1: syntax error: = unexpected
```

mmm maybe `last` is not supported in FreeBSD [bc(1)](https://www.freebsd.org/cgi/man.cgi?bc) to be used like this?

**Comment by jarun** [comment]
it's more like:

    bc
    last=10

**Comment by jarun** [comment]
ahh OK.

**Comment by jarun** [comment]
Can you try this patch?

```
diff --git a/src/bcal.c b/src/bcal.c
index b74f88a..31a34c4 100644
--- a/src/bcal.c
+++ b/src/bcal.c
@@ -210,6 +210,11 @@ static int try_bc(char *expr)
                exit(ret);
        }
 
+       if (write(pipe_pc[1], "\n", 1) != 1) {
+               log(ERROR, "write(5)! [%s]\n", strerror(errno));
+               exit(-1);
+       }
+
        /* parent */
        if (write(pipe_pc[1], "scale=10\n", 9) != 9) {
                log(ERROR, "write(1)! [%s]\n", strerror(errno));
```

**Comment by jarun** [comment]
Notice that we are using `dup2` to mimic STDIN from where `bc` should get input even in regular case.

**Comment by 0mp** [comment]
Nope, still the same problem.

Why printing a newline could help?

**Comment by jarun** [comment]
I was still thinking it was a problem with the complete buffer not flushed at once. But it isn't.

I went through the docs on `last` but I don't see a way to initialize it.

What do you see if you run:

    echo '2 + 3' | bc

**Comment by jarun** [comment]
I think the problem is on FreeBSD you cannot assign a custom value to last.

**Comment by jarun** [comment]
That also breaks the exchange on the value of the last result between `bcal` and `bc` on BSD.

**Comment by jarun** [comment]
What we can probably do is:

    bc
    print (value of lastres)
    \n
    \n
    //last gets set to lastres

**Comment by jarun** [comment]
try the following

    print 15
    15 //you have to press Enter here
    last
see if last shows 15.

**Comment by jarun** [comment]
But the problem is - there is no silent mode to the above would also be printed to the console.

**Comment by jarun** [comment]
Please try the following patch (without setting `last`) and confirm if it works:

```
diff --git a/src/bcal.c b/src/bcal.c
index b74f88a..177b56e 100644
--- a/src/bcal.c
+++ b/src/bcal.c
@@ -215,7 +215,7 @@ static int try_bc(char *expr)
                log(ERROR, "write(1)! [%s]\n", strerror(errno));
                exit(-1);
        }
-
+#if 0
        if (write(pipe_pc[1], "last=", 5) != 5) {
                log(ERROR, "write(2)! [%s]\n", strerror(errno));
                exit(-1);
@@ -238,7 +238,7 @@ static int try_bc(char *expr)
                log(ERROR, "write(5)! [%s]\n", strerror(errno));
                exit(-1);
        }
-
+#endif
        ret = strlen(expr);
        if (write(pipe_pc[1], expr, ret) != ret) {
                log(ERROR, "write(6)! [%s]\n", strerror(errno));
```

**Comment by 0mp** [comment]
I just think that you cannot assign values to `last` in FreeBSD bc(1) (at least I cannot find any information about in the manual page). On the other hand, GNU bc explicitly allows it ([see here](https://www.gnu.org/software/bc/manual/html_mono/bc.html#SEC15)).

**Comment by 0mp** [comment]
I've not seen the commit before commenting. I'll let you know if it works now.

**Comment by jarun** [comment]
OK. Thanks!

**Comment by 0mp** [comment]
Everything is green now!

**Comment by jarun** [comment]
Hurrah!
