### ISSUE TITLE
'quit' and 'exit' yield "ERROR: unknown unit"

### ISSUE THREAD

**Issue by sjmulder** [jarun/bcal#38]
Perhaps I'm misunderstanding how this is supposed to work but typing 'quit' or 'exit' at the prompt doesn't exit bcal as the changelog seems to imply:

    $ bcal -h | grep Version
    Version 2.3
    $ bcal
    q/double Enter -> quit, ? -> help
    bcal> quit
    ERROR: unknown unit
    bcal> exit
    ERROR: unknown unit

^D did work.

Using Debian 11.

**Comment by jarun** [comment]
As the prompt says, you have to press `Enter` twice (or `q`) to quit.

But I guess not supporting `quit` and `exit` is counter-intuitive. I'll add those.

**Comment by jarun** [comment]
Please confirm if the patch works as expected.

**Comment by sjmulder** [comment]
Yes, patch works :)

The prompt was clear but there was a changelog note about using 'exit' and 'quit', what was that referring to then?

**Comment by jarun** [comment]
That was for the bc/calc prompt. We are consistent now.
